# Generated by Django 5.1.5 on 2025-01-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_blog_author_coverimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="coverimage",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="coverimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
