# Generated by Django 5.1.5 on 2025-01-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_coverimage_created_at_coverimage_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
