# Generated by Django 5.1.5 on 2025-01-25 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("author", "0001_initial"),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blog",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="author.author"
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="cover_image",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cover_image",
                to="blog.coverimage",
            ),
        ),
        migrations.AlterField(
            model_name="blog",
            name="tags",
            field=models.ManyToManyField(to="blog.tags"),
        ),
    ]
